## Sharanya Assignment -8 

In [8]:
import numpy as np

In [15]:
#1.Write a Python Program to Add Two Matrices?

a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[6,7,8],
            [1,2,3]])
c=a+b
print("The addition of matrix")
print(c)

The addition of matrix
[[ 7  9 11]
 [ 5  7  9]]


In [19]:
#2. Write a Python Program to Multiply Two Matrices?

a=np.array([[1,2],
            [4,5]])
b=np.array([[6,7],
            [1,2]])
c=a.dot(b)
print("The multiplication of matrix")
print(c)

The multiplication of matrix
[[ 8 11]
 [29 38]]


In [20]:
#3. Write a Python Program to Transpose a Matrix?

a=np.array([[1,2,3],
            [4,5,6]])
a=a.transpose()
print("The transpose of the matrix")
print(a)

The transpose of the matrix
[[1 4]
 [2 5]
 [3 6]]


In [35]:
#4. Write a Python Program to Sort Words in Alphabetic Order?

s="Hello everyone here is my code for arranging it on alphabetically order"
s1=s.split(" ")
for i in range(len(s1)):
    s1[i]=s1[i].lower()
s=sorted(s1)
print(' '.join(s))

alphabetically arranging code everyone for hello here is it my on order


In [64]:
#5. Write a Python Program to Remove Punctuation From a String?

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
s="hello everyone!! here, we write code."
s1=""

for i in s:
   if i not in punctuations:
       s1= s1 + i
print(s1)

hello everyone here we write code
